var GAME_LEVELS = [
  ["                                                                               x",
   "                                                                               x",
   "                                                                               x",
   "                                                                               x",
   " x                                                                             x",
   " x                                                                             x",
   " x                                  x x                             t          x",
   " x                                                    x    xx                  x",
   " x                                             x  x                          x x",
   " x @   g                           xx xx   x                    x        x   x x",
   " x!x   x  x                                 r                       x        x x",
   " x!x!!!!!!x           x                     x                       x        x x",
   " xxxxxxxxxx           x              x    x x   x                            x x",
   "  x r                    x                   r                               x x",
   "  x       r             x  x             xx xx                            x  x x",
   "  x                                                              xx xx      xx x",
   "  x r     r                     t                           t    x   x      x  x",
   "  xxxx!!!xxxxx      xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx  x  xxxxxxx   xxxx  xx gx",
   "     xxxxx   x  r   x         x   x                  x  x  x       x          xx",
   "             x      x         x!!!x                  x!!!!!x       xxxxxxxx   !x",
   "             x!!!!!!x         x!!!x                  x!!!!!x!!!!!!!!!!!!!!!!!!!x",
   "             xxxxxxxx         xxxxx                  xxxxxxx!!!!!!!!!!!!!!!!!!!x",
   "                                                           xxxxxxxxxxxxxxxxxxxxx",
   "                                                                                "],
   
  ["   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                               ",
   "   x                     !!!                                                                                      ",
   "   x                      !                                                                                       ",
   "   x                      v                                                                                       ",
   "   x                                                                                                              ",
   "   x       @                                                                                                      ",
   "   xxxxxxxxxxxxxxxx                                                                                               ",
   "           g      x                                                                                               ",
   "                  x                                                                                               ",
   "                  xt                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                  xr                                                                                              ",
   "                                                                                                                  ",
   "                               t                                                                     x            ",
   "                            xx                                                                       x            ",
   "  x                                                                                                  x            ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                                                    x            ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                    x            ",
   "                                x                                                                    x            ",
   "                                x                                                                    x            ",
   "                                xt                      t        t      t      t      tg             x            ",
   "                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "                                                                                                                  ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
   
  ["              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             ",
   "              x                                                        x                             ",
   "              x                                                        x                             ",
   "              x                                                        x                             ",
   "              x                                                        x                             ",
   "              x                                                        x                             ",
   "              x                @                                       x                             ",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        x                             ",
   "                                              x                        x                             ",
   "                                              x                        x                             ",
   "                                              xt                       x                             ",
   "                                              x!x                      x                             ",
   "                                              xxx                      x                             ",
   "                                  x!!!!!!!!!!!x                        x                             ",
   "           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        x                             ",
   "           x                                                           x                             ",
   "           x                                                           x                             ",
   "           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      x!x                             ",
   "                                              x                      xxx                             ",
   "                                              x!x                      x                             ",
   "                                              xxx                      x                             ",
   "                          xxxxxxxxxxxxxxxxxxxxx                        x                             ",
   "                          x                                            x                             ",
   "                          x                                            x                             ",
   "                          xxxxxxxxxxxxxxxxxxxxx                       !xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                              x!                                                             x",
   "                                              x          t        t    t                                   g x",
   "                                              x                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                              x t        x           t          x                             ",
   "                                             gx      t                          x                             ",
   "                                              x!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!! x                             ",
   "                                                                                                              "],
   
   
  ["                   x         x   x   xxxxx   x   x        x       x       x   xxx   x   x                     ",
   "                   x          x x    x   x   x   x         x     x x     x     x    xx  x                     ",
   "                   x           x     x   x   x   x          x   x   x   x      x    x x x                     ",
   "                   x           x     x   x   x   x           x x     x x       x    x  xx                     ",
   "                   x           x     xxxxx    xxx             x       x       xxx   x   x                     ",
   "                   x                                                                                          ",
   "                   x                                    @                                                     ",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
